### ISSUE TITLE
color change suggestion

### ISSUE THREAD

**Issue by ktinthecloud** [ktinthecloud/github-crash-course#1]
I suggest we change the color on the style sheet.

```css
body {
  margin: 0;
  text-align: center;
  background-color: #322e2d;
  color: #8b2a0a;
}
```
